import type { LucideIcon } from "lucide-react";
import {
  Sparkles, Flower2, Mountain, HeartHandshake, Baby, BabyIcon,
  Camera, Wand2, Accessibility,
} from "lucide-react";

export type PresetCategory =
  | "Femme" | "Masc" | "Plus-Size" | "Inclusive"
  | "Child" | "Infant / Baby" | "Editorial" | "Fantasy / Alt" | "Accessibility";

export type Preset = {
  id: string;
  name: string;
  category: PresetCategory;
  description: string;
  prompt: string;
  tags: string[];
  autoToggleChild?: boolean;
  autoToggleInfant?: boolean;
  defaultPose?: string;
  accessibilityFlags?: string[];
  bodyType?: string;
  ageGroup?: "infant" | "child" | "teen" | "adult" | "elder";
};

export const CATEGORY_ORDER: PresetCategory[] = [
  "Femme", "Masc", "Plus-Size", "Inclusive",
  "Child", "Infant / Baby", "Editorial", "Fantasy / Alt", "Accessibility",
];

export const CATEGORY_META: Record<PresetCategory, { icon: LucideIcon; color: string }> = {
  "Femme":         { icon: Flower2,         color: "from-pink-400/40 to-rose-300/30" },
  "Masc":          { icon: Mountain,        color: "from-slate-400/40 to-blue-400/30" },
  "Plus-Size":     { icon: HeartHandshake,  color: "from-fuchsia-400/40 to-purple-400/30" },
  "Inclusive":     { icon: Sparkles,        color: "from-amber-300/40 to-orange-300/30" },
  "Child":         { icon: Baby,            color: "from-yellow-300/40 to-lime-300/30" },
  "Infant / Baby": { icon: BabyIcon,        color: "from-sky-300/40 to-cyan-200/30" },
  "Editorial":     { icon: Camera,          color: "from-zinc-500/40 to-zinc-300/30" },
  "Fantasy / Alt": { icon: Wand2,           color: "from-violet-500/40 to-indigo-400/30" },
  "Accessibility": { icon: Accessibility,   color: "from-emerald-400/40 to-teal-300/30" },
};

export const PRESETS: Preset[] = [
  // ── Femme ───────────────────────────────────────────────
  { id: "femme-curvy-brown", name: "Curvy brown-skin femme", category: "Femme",
    description: "Sleek dark bob, almond eyes, glowing deep brown skin.",
    prompt: "Curvy femme model, deep brown skin, sleek dark bob, almond eyes",
    tags: ["femme","curvy","brown skin","bob"], defaultPose: "Hands on hips, confident",
    bodyType: "curvy", ageGroup: "adult" },
  { id: "femme-black-goddess", name: "Black femme, natural texture", category: "Femme",
    description: "Rich dark chocolate skin, full lips, natural textured hair, commanding presence.",
    prompt: "Stunning Black femme model, rich dark chocolate skin, full lips, natural textured hair, commanding elegant presence, soft studio lighting",
    tags: ["femme","black","textured hair","elegant"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "adult" },
  { id: "femme-petite-asian", name: "Petite East-Asian femme", category: "Femme",
    description: "Jet black bangs, dewy skin, soft neutral expression.",
    prompt: "Petite east-asian femme, jet black bangs, dewy skin, neutral expression",
    tags: ["femme","petite","asian","bangs"], defaultPose: "Editorial 3/4 turn",
    bodyType: "petite", ageGroup: "adult" },
  { id: "femme-elder-silver", name: "Silver-pixie elder femme", category: "Femme",
    description: "Warm beige skin, expressive eyes, refined elegance.",
    prompt: "Elder model with silver pixie cut, warm beige skin, expressive eyes",
    tags: ["femme","elder","silver hair","mature"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "elder" },
  { id: "femme-fair-rose", name: "Fair rose femme", category: "Femme",
    description: "Porcelain skin, auburn waves, delicate features, soft gaze.",
    prompt: "Femme model with fair porcelain skin, flowing auburn waves, delicate features, soft romantic gaze, soft studio lighting",
    tags: ["femme","fair skin","auburn","white"], defaultPose: "Editorial 3/4 turn",
    bodyType: "slim", ageGroup: "adult" },

  // ── Masc ────────────────────────────────────────────────
  { id: "masc-athletic", name: "Athletic masc", category: "Masc",
    description: "Light brown skin, faded haircut, soft beard stubble.",
    prompt: "Masc model, athletic build, light brown skin, short faded hair, beard stubble",
    tags: ["masc","athletic","beard"], defaultPose: "Hands on hips, confident",
    bodyType: "athletic", ageGroup: "adult" },
  { id: "masc-black-king", name: "Black masc, full beard", category: "Masc",
    description: "Deep ebony skin, sharp jawline, full beard, confident magnetic gaze.",
    prompt: "Confident Black masc model, deep ebony skin, sharp jawline, full well-groomed beard, magnetic gaze, soft studio lighting",
    tags: ["masc","black","beard","confident"], defaultPose: "Standing neutral",
    bodyType: "athletic", ageGroup: "adult" },
  { id: "masc-tall-slim", name: "Tall slim masc", category: "Masc",
    description: "Lean frame, sharp jawline, tousled dark hair.",
    prompt: "Tall slim masc model, fair skin, sharp jawline, tousled dark hair, quiet confidence",
    tags: ["masc","tall","slim"], defaultPose: "Walking toward camera",
    bodyType: "slim", ageGroup: "adult" },
  { id: "masc-elder-grey", name: "Distinguished elder masc", category: "Masc",
    description: "Salt-and-pepper hair, warm olive skin, dignified expression.",
    prompt: "Distinguished elder masc, salt and pepper hair, warm olive skin, trimmed beard, dignified expression",
    tags: ["masc","elder","grey hair"], defaultPose: "Side profile",
    bodyType: "average", ageGroup: "elder" },
  { id: "masc-fair-blonde", name: "Fair blonde masc", category: "Masc",
    description: "Platinum blonde, icy blue eyes, sharp Nordic features.",
    prompt: "Masc model with fair skin, platinum blonde hair, icy blue eyes, sharp Nordic features, clean-shaven, confident posture",
    tags: ["masc","fair skin","blonde","white"], defaultPose: "Hands on hips, confident",
    bodyType: "slim", ageGroup: "adult" },
  { id: "masc-asian-sharp", name: "East-Asian sharp masc", category: "Masc",
    description: "Sleek black hair, monolid eyes, warm tan skin, modern edge.",
    prompt: "East-Asian masc model, sleek black hair styled modern, monolid eyes, warm tan skin, sharp jawline, contemporary fashion energy",
    tags: ["masc","asian","monolid","modern"], defaultPose: "Standing neutral",
    bodyType: "slim", ageGroup: "adult" },

  // ── Plus-Size ───────────────────────────────────────────
  { id: "plus-femme-strawberry", name: "Plus femme, strawberry waves", category: "Plus-Size",
    description: "Soft round features, freckled fair skin, romantic waves.",
    prompt: "Plus-size femme, soft round features, strawberry blonde waves, fair freckled skin",
    tags: ["plus-size","femme","redhead","freckles"], defaultPose: "Editorial 3/4 turn",
    bodyType: "plus", ageGroup: "adult" },
  { id: "plus-masc-bearded", name: "Plus masc, full beard", category: "Plus-Size",
    description: "Broad frame, warm tan skin, full beard, kind eyes.",
    prompt: "Plus-size masc, broad frame, warm tan skin, full beard, kind eyes",
    tags: ["plus-size","masc","beard"], defaultPose: "Standing neutral",
    bodyType: "plus", ageGroup: "adult" },
  { id: "plus-andro-locs", name: "Plus androgynous w/ locs", category: "Plus-Size",
    description: "Rich brown skin, shoulder-length locs, soft jaw.",
    prompt: "Plus-size androgynous person, rich brown skin, shoulder-length locs, soft jaw, calm gaze",
    tags: ["plus-size","androgynous","locs"], defaultPose: "Hands on hips, confident",
    bodyType: "plus", ageGroup: "adult" },

  // ── Inclusive ───────────────────────────────────────────
  { id: "incl-andro-olive", name: "Androgynous olive", category: "Inclusive",
    description: "Tall, soft freckles, natural curls, warm olive skin.",
    prompt: "Tall androgynous person, soft freckles, natural curls, warm olive skin",
    tags: ["androgynous","nonbinary","inclusive"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "adult" },
  { id: "incl-vitiligo", name: "Vitiligo model", category: "Inclusive",
    description: "Striking vitiligo patterning, shaved head, serene expression.",
    prompt: "Model with beautiful vitiligo patterning across face and arms, shaved head, serene expression, soft natural lighting",
    tags: ["vitiligo","inclusive","unique"], defaultPose: "Editorial 3/4 turn",
    bodyType: "average", ageGroup: "adult" },
  { id: "incl-hijab", name: "Hijabi femme", category: "Inclusive",
    description: "Warm brown skin, soft satin hijab, gentle smile.",
    prompt: "Hijabi femme model, warm brown skin, soft satin hijab in dusty rose, gentle smile, modest styling",
    tags: ["hijab","modest","inclusive"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "adult" },

  // ── Child ───────────────────────────────────────────────
  { id: "child-curly-7", name: "7yo with curls", category: "Child",
    description: "Cheerful 7-year-old, curly brown hair, freckles.",
    prompt: "Cheerful 7-year-old child, curly brown hair, light brown skin, freckles, playful expression",
    tags: ["child","kids","curly hair"], autoToggleChild: true,
    defaultPose: "Standing neutral", ageGroup: "child" },
  { id: "child-pigtails-5", name: "5yo with pigtails", category: "Child",
    description: "Bright 5-year-old, blonde pigtails, big blue eyes.",
    prompt: "Bright 5-year-old child, blonde pigtails, fair skin, big blue eyes, cheeky smile",
    tags: ["child","kids","pigtails"], autoToggleChild: true,
    defaultPose: "Hands on hips, confident", ageGroup: "child" },
  { id: "child-buzz-9", name: "9yo with buzzcut", category: "Child",
    description: "Cool 9-year-old, fresh buzzcut, deep brown skin.",
    prompt: "Cool 9-year-old child, fresh buzzcut, deep brown skin, confident grin",
    tags: ["child","kids","short hair"], autoToggleChild: true,
    defaultPose: "Walking toward camera", ageGroup: "child" },

  // ── Infant / Baby ───────────────────────────────────────
  { id: "infant-curls", name: "6mo, soft curls", category: "Infant / Baby",
    description: "Baby with soft brown curls, peaceful on a blanket.",
    prompt: "6-month-old baby, soft brown curls, warm fair skin, peaceful expression, lying on a soft cream blanket",
    tags: ["infant","baby","newborn"], autoToggleInfant: true,
    defaultPose: "Top-down on blanket", ageGroup: "infant" },
  { id: "infant-bald", name: "Newborn, bald", category: "Infant / Baby",
    description: "Bald newborn, golden tan skin, sleepy yawn.",
    prompt: "Newborn baby, bald, golden tan skin, sleepy yawn, on a soft beige blanket",
    tags: ["infant","newborn","bald"], autoToggleInfant: true,
    defaultPose: "Top-down on blanket", ageGroup: "infant" },
  { id: "infant-tuft", name: "9mo, black tuft", category: "Infant / Baby",
    description: "9-month baby with a black hair tuft, alert dark eyes.",
    prompt: "9-month-old baby with a small black hair tuft, deep brown skin, alert dark eyes, content smile, on a soft white blanket",
    tags: ["infant","baby"], autoToggleInfant: true,
    defaultPose: "Top-down on blanket", ageGroup: "infant" },

  // ── Editorial ───────────────────────────────────────────
  { id: "edit-runway", name: "Runway icon", category: "Editorial",
    description: "Sharp cheekbones, dramatic lighting, runway-ready.",
    prompt: "High-fashion runway model, sharp cheekbones, slicked-back hair, dramatic editorial lighting, couture energy",
    tags: ["editorial","runway","high fashion"], defaultPose: "Walking toward camera",
    bodyType: "slim", ageGroup: "adult" },
  { id: "edit-bw-pose", name: "B&W editorial", category: "Editorial",
    description: "Black-and-white editorial energy, soft shadows.",
    prompt: "Editorial model in soft black-and-white styling mood, neutral expression, sculptural pose, minimalist studio",
    tags: ["editorial","minimal","monochrome"], defaultPose: "Editorial 3/4 turn",
    bodyType: "slim", ageGroup: "adult" },
  { id: "edit-vintage", name: "Vintage couture", category: "Editorial",
    description: "60s-inspired bouffant, winged liner, classic glamour.",
    prompt: "Vintage couture model, 1960s bouffant, winged eyeliner, fair skin, classic Hollywood glamour",
    tags: ["editorial","vintage","retro"], defaultPose: "Side profile",
    bodyType: "slim", ageGroup: "adult" },

  // ── Fantasy / Alt ───────────────────────────────────────
  { id: "alt-elf", name: "Ethereal elf", category: "Fantasy / Alt",
    description: "Pointed ears, silver hair, otherworldly glow.",
    prompt: "Ethereal elf-inspired model, subtly pointed ears, long silver hair, pale luminous skin, otherworldly soft glow",
    tags: ["fantasy","elf","ethereal"], defaultPose: "Editorial 3/4 turn",
    bodyType: "slim", ageGroup: "adult" },
  { id: "alt-goth", name: "Goth alt", category: "Fantasy / Alt",
    description: "Inky black hair, pale skin, dramatic dark makeup.",
    prompt: "Alt goth model, inky long black hair, pale porcelain skin, dramatic dark makeup, silver jewelry",
    tags: ["alt","goth","dark"], defaultPose: "Side profile",
    bodyType: "slim", ageGroup: "adult" },
  { id: "alt-cyber", name: "Cyber-futurist", category: "Fantasy / Alt",
    description: "Iridescent makeup, sleek silver buzzcut, chrome accents.",
    prompt: "Cyber-futurist model, iridescent holographic makeup, sleek silver buzzcut, chrome jewelry accents, neutral expression",
    tags: ["fantasy","cyber","futuristic"], defaultPose: "Hands on hips, confident",
    bodyType: "athletic", ageGroup: "adult" },

  // ── Accessibility ───────────────────────────────────────
  { id: "a11y-wheelchair-femme", name: "Wheelchair femme", category: "Accessibility",
    description: "Long auburn hair, porcelain skin, styled in a wheelchair.",
    prompt: "Wheelchair user, femme, long auburn hair, porcelain skin, gentle smile, styled fashion pose",
    tags: ["wheelchair","disability","accessibility","femme"],
    accessibilityFlags: ["wheelchair"], defaultPose: "Wheelchair, styled pose",
    bodyType: "average", ageGroup: "adult" },
  { id: "a11y-prosthetic", name: "Prosthetic leg model", category: "Accessibility",
    description: "Confident model with a sleek prosthetic leg.",
    prompt: "Confident model with a sleek modern prosthetic leg visible, athletic build, warm brown skin, short curly hair",
    tags: ["prosthetic","limb difference","accessibility"],
    accessibilityFlags: ["prosthetic"], defaultPose: "Standing neutral",
    bodyType: "athletic", ageGroup: "adult" },
  { id: "a11y-cane", name: "Cane user, elder", category: "Accessibility",
    description: "Elegant elder with a styled wooden cane.",
    prompt: "Elegant elder model using a styled wooden cane, silver waves, warm beige skin, refined posture",
    tags: ["cane","mobility aid","elder","accessibility"],
    accessibilityFlags: ["cane"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "elder" },
  { id: "a11y-seated", name: "Seated fashion pose", category: "Accessibility",
    description: "Styled seated pose for paralysis or seated styling, no visible aid.",
    prompt: "Model seated upright in a relaxed editorial fashion pose, full body visible, natural proportions, calm confident expression, clothing draping naturally over the lap and legs",
    tags: ["seated","paralysis","accessibility"],
    accessibilityFlags: ["seated"], defaultPose: "Seated, styled pose",
    bodyType: "average", ageGroup: "adult" },
  { id: "a11y-walker-elder", name: "Walker user, elder masc", category: "Accessibility",
    description: "Elder masc model using a mobility walker, dignified standing posture.",
    prompt: "Elder masc model using a modern mobility walker, salt-and-pepper hair, warm beige skin, dignified standing posture, full body visible",
    tags: ["walker","mobility aid","elder","accessibility"],
    accessibilityFlags: ["walker"], defaultPose: "Walker, standing styled",
    bodyType: "average", ageGroup: "elder" },
  { id: "a11y-crutches", name: "Crutches user, athletic", category: "Accessibility",
    description: "Athletic model balanced on forearm crutches.",
    prompt: "Athletic model using forearm crutches, balanced editorial fashion pose, warm tan skin, short dark hair, confident expression, full body visible",
    tags: ["crutches","mobility aid","accessibility"],
    accessibilityFlags: ["crutches"], defaultPose: "Crutches, balanced pose",
    bodyType: "athletic", ageGroup: "adult" },
  { id: "a11y-upper-limb", name: "Upper-limb difference", category: "Accessibility",
    description: "Model with a visible upper-limb difference, preserved as-is.",
    prompt: "Confident model with a visible upper-limb difference (limb difference preserved exactly, not regenerated), warm brown skin, natural curls, soft editorial expression, full body visible",
    tags: ["amputee","limb difference","accessibility"],
    accessibilityFlags: ["limb difference","amputee"], defaultPose: "Standing neutral",
    bodyType: "average", ageGroup: "adult" },
  { id: "a11y-little-person-femme", name: "Little person, femme", category: "Accessibility",
    description: "Femme little-person model with accurate proportions.",
    prompt: "Femme little-person fashion model, accurate natural proportions for a little person, soft auburn waves, warm fair skin, confident editorial pose, full body visible",
    tags: ["little person","dwarfism","accessibility","femme"],
    accessibilityFlags: ["little person"], defaultPose: "Standing neutral",
    bodyType: "petite", ageGroup: "adult" },
  { id: "a11y-little-person-masc", name: "Little person, masc", category: "Accessibility",
    description: "Masc little-person model with accurate proportions.",
    prompt: "Masc little-person fashion model, accurate natural proportions for a little person, short dark hair, warm tan skin, confident editorial pose, full body visible",
    tags: ["little person","dwarfism","accessibility","masc"],
    accessibilityFlags: ["little person"], defaultPose: "Standing neutral",
    bodyType: "petite", ageGroup: "adult" },
  { id: "a11y-child-wheelchair", name: "Child wheelchair user", category: "Accessibility",
    description: "Cheerful child styled in a wheelchair, full body visible.",
    prompt: "Cheerful 8-year-old child wheelchair user, light brown skin, curly hair, gentle smile, modest age-appropriate fashion styling, full body visible with wheelchair preserved",
    tags: ["wheelchair","child","accessibility"], autoToggleChild: true,
    accessibilityFlags: ["wheelchair"], defaultPose: "Wheelchair, styled pose",
    bodyType: "petite", ageGroup: "child" },
  { id: "a11y-infant-limb", name: "Infant with limb difference", category: "Accessibility",
    description: "Infant with a visible limb difference, lying modestly on a blanket.",
    prompt: "6-month-old baby with a visible limb difference (preserved exactly, not regenerated), warm fair skin, peaceful expression, lying on a soft cream blanket",
    tags: ["infant","limb difference","accessibility"], autoToggleInfant: true,
    accessibilityFlags: ["limb difference"], defaultPose: "Top-down on blanket",
    bodyType: "average", ageGroup: "infant" },
];

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}