/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMoodboardsRouteImport } from './routes/_authenticated/moodboards'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedLookbookRouteImport } from './routes/_authenticated/lookbook'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedClosetRouteImport } from './routes/_authenticated/closet'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicMasterRecoveryRouteImport } from './routes/api/public/master-recovery'
import { Route as AuthenticatedLookbookCompareRouteImport } from './routes/_authenticated/lookbook.compare'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoodboardsRoute = AuthenticatedMoodboardsRouteImport.update({
  id: '/moodboards',
  path: '/moodboards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLookbookRoute = AuthenticatedLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClosetRoute = AuthenticatedClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMasterRecoveryRoute = ApiPublicMasterRecoveryRouteImport.update({
  id: '/api/public/master-recovery',
  path: '/api/public/master-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLookbookCompareRoute =
  AuthenticatedLookbookCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedLookbookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/closet': typeof AuthenticatedClosetRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/lookbook': typeof AuthenticatedLookbookRouteWithChildren
  '/models': typeof AuthenticatedModelsRoute
  '/moodboards': typeof AuthenticatedMoodboardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/lookbook/compare': typeof AuthenticatedLookbookCompareRoute
  '/api/public/master-recovery': typeof ApiPublicMasterRecoveryRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/closet': typeof AuthenticatedClosetRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/lookbook': typeof AuthenticatedLookbookRouteWithChildren
  '/models': typeof AuthenticatedModelsRoute
  '/moodboards': typeof AuthenticatedMoodboardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/lookbook/compare': typeof AuthenticatedLookbookCompareRoute
  '/api/public/master-recovery': typeof ApiPublicMasterRecoveryRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/closet': typeof AuthenticatedClosetRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/lookbook': typeof AuthenticatedLookbookRouteWithChildren
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/moodboards': typeof AuthenticatedMoodboardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/lookbook/compare': typeof AuthenticatedLookbookCompareRoute
  '/api/public/master-recovery': typeof ApiPublicMasterRecoveryRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/closet'
    | '/collections'
    | '/lookbook'
    | '/models'
    | '/moodboards'
    | '/settings'
    | '/studio'
    | '/lookbook/compare'
    | '/api/public/master-recovery'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/closet'
    | '/collections'
    | '/lookbook'
    | '/models'
    | '/moodboards'
    | '/settings'
    | '/studio'
    | '/lookbook/compare'
    | '/api/public/master-recovery'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/closet'
    | '/_authenticated/collections'
    | '/_authenticated/lookbook'
    | '/_authenticated/models'
    | '/_authenticated/moodboards'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/lookbook/compare'
    | '/api/public/master-recovery'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicMasterRecoveryRoute: typeof ApiPublicMasterRecoveryRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moodboards': {
      id: '/_authenticated/moodboards'
      path: '/moodboards'
      fullPath: '/moodboards'
      preLoaderRoute: typeof AuthenticatedMoodboardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lookbook': {
      id: '/_authenticated/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof AuthenticatedLookbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/closet': {
      id: '/_authenticated/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof AuthenticatedClosetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/master-recovery': {
      id: '/api/public/master-recovery'
      path: '/api/public/master-recovery'
      fullPath: '/api/public/master-recovery'
      preLoaderRoute: typeof ApiPublicMasterRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lookbook/compare': {
      id: '/_authenticated/lookbook/compare'
      path: '/compare'
      fullPath: '/lookbook/compare'
      preLoaderRoute: typeof AuthenticatedLookbookCompareRouteImport
      parentRoute: typeof AuthenticatedLookbookRoute
    }
  }
}

interface AuthenticatedLookbookRouteChildren {
  AuthenticatedLookbookCompareRoute: typeof AuthenticatedLookbookCompareRoute
}

const AuthenticatedLookbookRouteChildren: AuthenticatedLookbookRouteChildren = {
  AuthenticatedLookbookCompareRoute: AuthenticatedLookbookCompareRoute,
}

const AuthenticatedLookbookRouteWithChildren =
  AuthenticatedLookbookRoute._addFileChildren(
    AuthenticatedLookbookRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClosetRoute: typeof AuthenticatedClosetRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedLookbookRoute: typeof AuthenticatedLookbookRouteWithChildren
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedMoodboardsRoute: typeof AuthenticatedMoodboardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClosetRoute: AuthenticatedClosetRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedLookbookRoute: AuthenticatedLookbookRouteWithChildren,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedMoodboardsRoute: AuthenticatedMoodboardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicMasterRecoveryRoute: ApiPublicMasterRecoveryRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
